/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package samplesourcepackage;

import com.nike.vault.client.VaultClient;
import com.nike.vault.client.VaultClientFactory;

public class Library {
    public boolean someLibraryMethod() {
    	VaultClient vaultClient = VaultClientFactory.getClient();
        return true;
    }
}
